spring.application.name=RegistryServer

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Service URL
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# Actuator for Health Monitoring
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always