server.port=8080
# Tells Spring to use the Servlet (WebMVC) stack
spring.main.web-application-type=servlet
spring.cloud.gateway.server.webmvc.enabled=true

# JWT Secret (Must match User Service)
jwt.secret=${SECRET_STRING:My_very_long_Secret_Key_That_is_at_least_32_characters_long_for_HS256}

# Eureka Registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/