server.port=8080
# Eureka Registry Location
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 1. User Service Routes
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# 2. Account Service Routes
spring.cloud.gateway.routes[1].id=account-service
spring.cloud.gateway.routes[1].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/accounts/**

# 3. Transaction Service Routes
spring.cloud.gateway.routes[2].id=transaction-service
spring.cloud.gateway.routes[2].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=P ath=/api/v1/transactions/**