version: '3.8'

services:
  transaction-service:
    build: .
    container_name: transaction-service
    ports:
      - "8083:8083"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      # Here we pass the ENV variable that your application.properties expects
      # Note: We use 'mysql-db' as the hostname because that is the service name
      - DB_URL=jdbc:mysql://mysql-db:3306/docker_transaction?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_URL=http://host.docker.internal:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway" # Required for Linux, good practice for Windows

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_transaction
    volumes:
      # Format: [Volume Name] : [Internal Path in Container]
      - transaction-db-data:/var/lib/mysql
    ports:
      - "3307:3306" # Local machine hits 3307, Container uses 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10


volumes:
  transaction-db-data: